name: .NET

on:
  
  workflow_dispatch:
  
  push:
    branches:
    - master
  
  pull_request:
    branches:
    - master

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
      
    - name: Publish (on version change)
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: FineDataFlow.Engine.FileLineReader/FineDataFlow.Engine.FileLineReader.csproj
        PACKAGE_NAME: FineDataFlow.Engine.FileLineReader
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
